services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - test-network

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./doc:/app/doc
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
